/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./views/AppRegister/step1 copy 2.vue')['default']
    App: typeof import('./App.vue')['default']
    AppCart: typeof import('./views/AppCart/index.vue')['default']
    AppDetail: typeof import('./views/AppDetail/index.vue')['default']
    AppList: typeof import('./views/AppList/index.vue')['default']
    AppLogin: typeof import('./views/AppLogin/index.vue')['default']
    AppMain: typeof import('./views/AppMain/index.vue')['default']
    AppMine: typeof import('./views/AppMine/index.vue')['default']
    AppRegiste: typeof import('./views/AppRegiste/index.vue')['default']
    AppRegister: typeof import('./views/AppRegister/index.vue')['default']
    AppSort: typeof import('./views/AppSort/index.vue')['default']
    CommonFooter: typeof import('./components/CommonFooter.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader.vue')['default']
    CommonList: typeof import('./components/CommonList.vue')['default']
    copy: typeof import('./views/AppRegister/step1 copy.vue')['default']
    MainBanner: typeof import('./views/AppMain/MainBanner.vue')['default']
    MainNav: typeof import('./views/AppMain/MainNav.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1: typeof import('./views/AppRegister/step1.vue')['default']
    Step2: typeof import('./views/AppRegister/step2.vue')['default']
    Step3: typeof import('./views/AppRegister/step3.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    'VanCheckbox()': typeof import('vant/es')['Checkbox()']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
